#!/usr/bin/env python3
"""Generate the drive-MCU wiring schematic (KiCAD 10, format 20260306).

Block-level harness diagram: NUCLEO-G474RE <-> 4x VNH5019 <-> 4x goBILDA 5203
motors/encoders, plus power rails, current-sense, faults, E-stop and Vbat
divider. Connectivity is by named nets (global labels placed on pin ends),
matching firmware/drive_mcu/docs/pin_map.md and include/pins.h — change those
and this together.

    python3 tools/kicad/gen_drive_wiring.py
    python3 tools/kicad/check_drive_wiring.py     # netlist assertions
    python3 tools/kicad/render_schematics.py      # SVG for the figures/site

`NUC_NETS` is module-level on purpose: tools/check_integration_map.py asserts it
against the pin-map document, so the schematic and the firmware pin map cannot
drift apart silently.

Output: electronics/KiCAD/drive_mcu_wiring/drive_mcu_wiring.kicad_sch (+ .kicad_pro)
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from kicad_sch import Sheet, snap  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "electronics" / "KiCAD" / "drive_mcu_wiring"

# ---------------------------------------------------------------- symbols --
# pins: (name, side, slot) — side L/R/T/B, slot = position index on that side
WHEELS = ["LF", "LR", "RF", "RR"]

NUCLEO_PINS = [
    # encoders (left side)
    ("PA0 TIM2_CH1", "L", 0), ("PA1 TIM2_CH2", "L", 1),
    ("PA6 TIM3_CH1", "L", 2), ("PA7 TIM3_CH2", "L", 3),
    ("PB6 TIM4_CH1", "L", 4), ("PB7 TIM4_CH2", "L", 5),
    ("PC6 TIM8_CH1", "L", 6), ("PC7 TIM8_CH2", "L", 7),
    # ADC + safety (left, lower group)
    ("PC0 ADC1_IN6", "L", 9), ("PC1 ADC1_IN7", "L", 10),
    ("PC2 ADC1_IN8", "L", 11), ("PC3 ADC1_IN9", "L", 12),
    ("PC4 ADC2_IN5", "L", 13), ("PB12 ESTOP_IN", "L", 14),
    # PWM + direction + faults (right side)
    ("PA8 TIM1_CH1", "R", 0), ("PA9 TIM1_CH2", "R", 1),
    ("PA10 TIM1_CH3", "R", 2), ("PA11 TIM1_CH4", "R", 3),
    ("PB0", "R", 5), ("PB1", "R", 6), ("PB2", "R", 7), ("PB10", "R", 8),
    ("PB4", "R", 9), ("PB5", "R", 10), ("PB13", "R", 11), ("PB14", "R", 12),
    ("PC10", "R", 14), ("PC11", "R", 15), ("PC12", "R", 16), ("PD2", "R", 17),
    # power (top)
    ("E5V", "T", 0), ("3V3", "T", 1), ("GND", "T", 2),
]

VNH_PINS = [
    ("VDD", "L", 0), ("INA", "L", 1), ("INB", "L", 2), ("PWM", "L", 3),
    ("EN/DIAG", "L", 4), ("CS", "L", 5), ("GND", "L", 6),
    ("VIN", "R", 0), ("OUTA", "R", 2), ("OUTB", "R", 3), ("GND_P", "R", 5),
]

MOTOR_PINS = [
    ("M+", "L", 0), ("M-", "L", 1),
    ("ENC_3V3", "L", 3), ("ENC_A", "L", 4), ("ENC_B", "L", 5), ("ENC_GND", "L", 6),
]

R_PINS = [("1", "T", 0), ("2", "B", 0)]

# ------------------------------------------------------------------- nets --
# MCU pin function -> net name. The single machine-readable statement of the
# drive harness; cross-checked against pin_map.md by check_integration_map.py.
NUC_NETS = {
    "PA0 TIM2_CH1": "LF_ENC_A", "PA1 TIM2_CH2": "LF_ENC_B",
    "PA6 TIM3_CH1": "LR_ENC_A", "PA7 TIM3_CH2": "LR_ENC_B",
    "PB6 TIM4_CH1": "RF_ENC_A", "PB7 TIM4_CH2": "RF_ENC_B",
    "PC6 TIM8_CH1": "RR_ENC_A", "PC7 TIM8_CH2": "RR_ENC_B",
    "PC0 ADC1_IN6": "LF_CS", "PC1 ADC1_IN7": "LR_CS",
    "PC2 ADC1_IN8": "RF_CS", "PC3 ADC1_IN9": "RR_CS",
    "PC4 ADC2_IN5": "VBAT_SENSE", "PB12 ESTOP_IN": "ESTOP_STATE",
    "PA8 TIM1_CH1": "LF_PWM", "PA9 TIM1_CH2": "LR_PWM",
    "PA10 TIM1_CH3": "RF_PWM", "PA11 TIM1_CH4": "RR_PWM",
    "PB0": "LF_INA", "PB1": "LF_INB", "PB2": "LR_INA", "PB10": "LR_INB",
    "PB4": "RF_INA", "PB5": "RF_INB", "PB13": "RR_INA", "PB14": "RR_INB",
    "PC10": "LF_FLT", "PC11": "LR_FLT", "PC12": "RF_FLT", "PD2": "RR_FLT",
    "E5V": "+5V_RAIL", "3V3": "+3V3", "GND": "GND",
}


def vnh_nets(w: str) -> dict[str, str]:
    return {"VDD": "+3V3", "INA": f"{w}_INA", "INB": f"{w}_INB",
            "PWM": f"{w}_PWM", "EN/DIAG": f"{w}_FLT", "CS": f"{w}_CS",
            "GND": "GND", "VIN": "+12V_BUS", "GND_P": "GND_PWR",
            "OUTA": f"{w}_M+", "OUTB": f"{w}_M-"}


def motor_nets(w: str) -> dict[str, str]:
    return {"M+": f"{w}_M+", "M-": f"{w}_M-", "ENC_3V3": "+3V3",
            "ENC_A": f"{w}_ENC_A", "ENC_B": f"{w}_ENC_B", "ENC_GND": "GND"}


NOTES = [
    ("Buddy drive MCU wiring — block-level harness (nets by label)", 20, 20, 2.5),
    ("Source of truth: firmware/drive_mcu/docs/pin_map.md + include/pins.h;", 20, 26, 1.5),
    ("generated by tools/kicad/gen_drive_wiring.py — regenerate, don't hand-edit.", 20, 30, 1.5),
    ("PA2/PA3 = USART2 -> ST-LINK VCP -> Jetson USB (on-board, not wired here). ADR-0006.", 20, 36, 1.5),
    ("Power: +12V_BUS via 60 A fuse from 3S pack (ADR-0005); +5V_RAIL buck powers Nucleo E5V (JP3=E5V);", 20, 40, 1.5),
    ("+3V3 from Nucleo LDO feeds encoders + VNH5019 logic. GND_PWR = motor return, star at battery.", 20, 44, 1.5),
    ("ESTOP_STATE: contact off the E-stop chain, reporting only — E-stop cuts +12V_BUS upstream.", 20, 48, 1.5),
    ("EN/DIAG lines need 3V3 pull-ups (VNH5019 carrier has them); CS valid only while driving.", 20, 52, 1.5),
    ("System-level power distribution and the Jetson/sensor interconnect are a separate", 20, 58, 1.5),
    ("sheet: electronics/KiCAD/system_wiring/ (tools/kicad/gen_system_wiring.py).", 20, 62, 1.5),
]

NUC_W, NUC_H = 27.94, 25.4
VNH_W, VNH_H = 17.78, 11.43
MOT_W, MOT_H = 20.32, 11.43
RW, RH = 2.54, 5.08


def main() -> int:
    sh = Sheet("drive_mcu_wiring", "Buddy drive MCU wiring", "2026-07-15")
    sh.define("NUCLEO_G474RE", NUCLEO_PINS, NUC_W, NUC_H)
    sh.define("VNH5019_CARRIER", VNH_PINS, VNH_W, VNH_H)
    sh.define("GOBILDA_5203", MOTOR_PINS, MOT_W, MOT_H)
    sh.define("R_DIV", R_PINS, RW, RH)

    nucleo = sh.place("NUCLEO_G474RE", "U1", "NUCLEO-G474RE (drive MCU)",
                      snap(90), snap(130))
    sh.nets(nucleo, NUC_NETS)

    for i, w in enumerate(WHEELS):
        vy = snap(55 + i * 55)
        drv = sh.place("VNH5019_CARRIER", f"U{i + 2}", f"VNH5019 ({w})", snap(210), vy)
        sh.nets(drv, vnh_nets(w))
        mot = sh.place("GOBILDA_5203", f"M{i + 1}", f"goBILDA 5203 ({w})", snap(330), vy)
        sh.nets(mot, motor_nets(w))

    # Vbat divider (10:1 into PC4)
    r1 = sh.place("R_DIV", "R1", "90k (10:1 upper)", snap(60), snap(215))
    sh.nets(r1, {"1": "+12V_BUS", "2": "VBAT_SENSE"})
    r2 = sh.place("R_DIV", "R2", "10k (10:1 lower)", snap(60), snap(240))
    sh.nets(r2, {"1": "VBAT_SENSE", "2": "GND"})

    for s, x, y, size in NOTES:
        sh.text(s, x, y, size)

    sch = sh.write(OUT)
    print(f"wrote {sch.relative_to(ROOT)} ({sh.net_count} net labels)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
