/* ============================ GENERATED FILE ============================
 * DO NOT EDIT. Generated by tools/build.py from design_params.yaml (firmware
 * section) + requirements yaml. Edit those and re-run `python3 tools/build.py`.
 * ======================================================================= */
#ifndef BUDDY_CONFIG_H
#define BUDDY_CONFIG_H

#define BUDDY_VEL_LIMIT_MMPS 750   /* teleop max, requirements yaml */
#define BUDDY_CURRENT_LIMIT_MA 8000 /* ADR-0005 driver limit */
#define BUDDY_WATCHDOG_MS 200       /* REQ_SAFE_002 */
#define BUDDY_TELEMETRY_HZ 100
#define BUDDY_CONTROL_HZ 1000
#define BUDDY_PWM_HZ 20000
#define BUDDY_WHEEL_RADIUS_UM 48000   /* micrometers, integer-exact */
#define BUDDY_ENC_COUNTS_PER_REV 753     /* 4x-decoded counts at output shaft */

#endif /* BUDDY_CONFIG_H */
