#!/usr/bin/env python3
"""Render the Buddy power budget figure.

Left panel:  peak bus current by scenario vs the protection chain.
Right panel: average-power stack for expected vs allocation mission models.

All values from buddy_calcs.power (design_params.yaml + requirements yaml).
Regenerated by tools/build.py, or directly:

    python3 tools/figures/plot_power_budget.py [--png [path]]

Output: assets/figures/power_budget.svg
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
from buddy_calcs import power  # noqa: E402

# palette — one definition for every Buddy figure (tools/figures/palette.py).
# BLUE = designed operating scenarios; CRITICAL = fault scenario (status red,
# never an operating point); STACK = the fixed categorical order.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from palette import (  # noqa: E402
    AXIS, BLUE, CRITICAL, GRID, INK, MPL_SANS, MUTED, PURPLE, STACK, SURFACE,
)


def peak_panel(ax, s):
    names = ["flat\ncruise", "ramp +\naccel", "pivot\nbreakaway",
             "stall,\ndriver-limited", "+ future\ndual arms", "stall,\nUNLIMITED\n(fault)"]
    scen = list(s.scen_total.values())
    vals = scen[:4] + [s.peak_with_arms] + [scen[4]]
    colors = [BLUE] * 4 + [PURPLE] + [CRITICAL]
    bars = ax.bar(names, vals, color=colors, width=0.62, zorder=3)
    for b, v in zip(bars, vals):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.7, f"{v:.0f} A",
                ha="center", fontsize=9, color=INK, fontweight="bold", zorder=4)

    for level, label in [(s.bms_min_a, f"BMS continuous ≥ {s.bms_min_a:g} A"),
                         (s.fuse_a, f"main fuse {s.fuse_a:g} A (slow-blow)")]:
        ax.axhline(level, color=MUTED, linestyle=(0, (5, 4)), lw=1.2, zorder=2)
        ax.text(-0.4, level + 0.6, label, fontsize=8.5, color=MUTED, zorder=4)

    ax.set_ylim(0, s.fuse_a * 1.18)
    ax.set_ylabel("Bus current (A)", fontsize=10, color=MUTED)
    ax.set_title("Peak current by scenario vs protection chain",
                 fontsize=11, color=INK, loc="left")
    ax.grid(True, axis="y", color=GRID, lw=0.8, zorder=0)
    ax.tick_params(colors=MUTED, labelsize=8.5)


def energy_panel(ax, s):
    models = {
        f"expected\n({s.wh_expected:.0f} Wh -> {s.ah_expected:.1f} Ah)": [
            ("drive", s.p_drive_avg),
            ("Jetson", s.duty["jetson_average_w"]),
            ("camera*", s.loads["rgbd_camera_reserve"]),
            ("LiDAR*", s.loads["lidar_2d_reserve"]),
            ("MCU", s.loads["mcu_drivers_logic"]),
        ],
        f"allocation\n({s.wh_allocation:.0f} Wh -> {s.ah_allocation:.1f} Ah)": [
            ("drive", s.p_drive_avg),
            ("Jetson", s.loads["jetson_orin_nano"]),
            ("camera*", s.loads["rgbd_camera_reserve"]),
            ("LiDAR*", s.loads["lidar_2d_reserve"]),
            ("MCU", s.loads["mcu_drivers_logic"]),
            ("expansion*", s.loads["expansion_reserve"]),
        ],
        f"+ dual arms\n({s.wh_future:.0f} Wh -> {s.ah_future:.1f} Ah)": [
            ("drive", s.p_drive_avg),
            ("Jetson", s.loads["jetson_orin_nano"]),
            ("camera*", s.loads["rgbd_camera_reserve"]),
            ("LiDAR*", s.loads["lidar_2d_reserve"]),
            ("MCU", s.loads["mcu_drivers_logic"]),
            ("expansion*", s.loads["expansion_reserve"]),
            ("arms*", s.arms["avg_power_w"]),
        ],
    }
    for xi, (model, parts) in enumerate(models.items()):
        bottom = 0.0
        for pi, (name, w) in enumerate(parts):
            ax.bar([model], [w], bottom=bottom, color=STACK[pi], width=0.5, zorder=3)
            if w >= 4:
                ax.text(xi, bottom + w / 2, f"{name} {w:.0f} W", ha="center",
                        va="center", fontsize=8.5, color="#ffffff",
                        fontweight="bold", zorder=4)
            bottom += w
        ax.text(xi, bottom + 1.2, f"{bottom:.0f} W avg", ha="center", fontsize=10,
                color=INK, fontweight="bold", zorder=4)

    ax.set_ylim(0, s.p_avg_future * 1.22)
    ax.set_ylabel("Average power (W)", fontsize=10, color=MUTED)
    ax.set_title(f"Mission average power -> battery for {s.runtime_h * 60:.0f} min",
                 fontsize=11, color=INK, loc="left")
    ax.text(0.5, -0.16, "* reserved allocation — hardware not selected yet",
            transform=ax.transAxes, ha="center", fontsize=8.5, color=MUTED)
    ax.grid(True, axis="y", color=GRID, lw=0.8, zorder=0)
    ax.tick_params(colors=MUTED, labelsize=9)


def main() -> int:
    s = power.summary()
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": MPL_SANS,
        "svg.fonttype": "none",
        "svg.hashsalt": "buddy",
    })
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.2, 4.8), dpi=100,
                                   gridspec_kw={"width_ratios": [1.45, 1]})
    fig.patch.set_facecolor(SURFACE)
    for ax in (ax1, ax2):
        ax.set_facecolor(SURFACE)
        for spine in ("top", "right"):
            ax.spines[spine].set_visible(False)
        for spine in ("left", "bottom"):
            ax.spines[spine].set_color(AXIS)
    peak_panel(ax1, s)
    energy_panel(ax2, s)
    fig.suptitle(f"Buddy power budget — 3S Li-ion bus ({s.v:g} V nominal), "
                 f"driver limit {s.i_lim:g} A/motor",
                 fontsize=12, color=INK, x=0.02, ha="left")
    fig.tight_layout(rect=(0, 0.02, 1, 0.94))

    out = REPO / "assets" / "figures" / "power_budget.svg"
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, format="svg", bbox_inches="tight", facecolor=SURFACE,
                metadata={"Date": None})
    print(f"wrote {out.relative_to(REPO)}")
    if len(sys.argv) > 1 and sys.argv[1] == "--png":
        png = Path(sys.argv[2]) if len(sys.argv) > 2 else out.with_suffix(".png")
        fig.savefig(png, format="png", dpi=160, bbox_inches="tight", facecolor=SURFACE)
        print(f"wrote {png}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
