#!/usr/bin/env python3
"""Buddy parametric build — regenerate everything from design_params.yaml.

    python3 tools/build.py

Steps:
  1. Validate derived geometry against the requirements yaml, and check the
     integration map against the pin map, the protocol spec and the bridge
     node (both fail loudly).
  2. Generate robot_ws/src/buddy_description/urdf/buddy_params.xacro.
  3. Execute marimo notebooks in docs/analysis/ and export each to markdown
     (same basename, .md) with website frontmatter.
  4. Regenerate figures (tools/figures/plot_*.py) — quantitative figures via
     matplotlib, integration diagrams via tools/figures/blockdiagram.py, each
     one layout-audited before it is written.
  5. Regenerate robot_ws/analysis/torque_sweep.csv.
  6. Regenerate both KiCAD schematics and export their PDFs (skipped when
     kicad-cli is not installed).

Everything generated is committed to git so the repo always shows current,
rendered documents and diffs of numbers become visible history.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))

import buddy_calcs  # noqa: E402
from buddy_calcs import P, base_center_z, ground_clearance  # noqa: E402
from buddy_calcs import power as buddy_power  # noqa: E402
import check_integration_map  # noqa: E402

# Website frontmatter for exported analysis notebooks, keyed by notebook stem.
FRONTMATTER = {
    "drive_torque_and_pivot_scrub": {
        "title": "Analysis — Drive Torque and Pivot Scrub Derivations",
        "date": "2026-07-11",
        "type": "analysis",
        "tags": "[mechanical]",
        "summary": "Full derivations, symbol definitions, numeric substitutions, "
                   "and validity limits for the drive-motor torque envelope.",
        "figures": "[assets/figures/drive_fbd.svg]",
    },
    "power_budget_and_battery": {
        "title": "Analysis — Power Budget and Battery Sizing",
        "date": "2026-07-12",
        "type": "analysis",
        "tags": "[mechanical, electrical]",
        "summary": "Why 4x 9.2 A stall is a designed ceiling, not a battery "
                   "requirement — peak scenarios, protection chain, and capacity "
                   "sizing with reserves for unchosen hardware.",
        "figures": "[assets/figures/power_budget.svg]",
    },
}

XACRO_TEMPLATE = """<?xml version="1.0"?>
<!-- ============================ GENERATED FILE ============================
     DO NOT EDIT. Generated by tools/build.py from design_params.yaml — edit
     that file and re-run `python3 tools/build.py`. Values here feed RViz,
     Gazebo physics, and the diff-drive plugin at once.

     NOTE (placeholder warning): the chassis box is a placeholder and almost
     certainly not the final shape. Revisit with chassis CAD — in
     design_params.yaml, never here.
     ======================================================================= -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Body box -->
  <xacro:property name="base_length" value="{c[length_m]:g}"/>
  <xacro:property name="base_width"  value="{c[width_m]:g}"/>
  <xacro:property name="base_height" value="{c[height_m]:g}"/>
  <xacro:property name="base_mass"   value="{c[mass_kg]:g}"/>

  <!-- Inertial provenance: "{c[mass_source]}".
       measured_inertia=false -> the URDF derives a uniform solid-box inertia
       about the geometric centre (the long-standing placeholder behaviour).
       Fill chassis.com_m and chassis.inertia_kgm2 in design_params.yaml from
       SolidWorks mass properties and this flips to true, so the sim inherits
       the real mass distribution — which is what the 20 deg ramp tipping case
       actually depends on. See docs/system_model/chassis_interface.md -->
  <xacro:property name="measured_inertia" value="{measured}"/>
  <xacro:property name="com_x" value="{com[x]:g}"/>
  <xacro:property name="com_y" value="{com[y]:g}"/>
  <xacro:property name="com_z" value="{com[z]:g}"/>
  <xacro:property name="base_ixx" value="{inr[ixx]:g}"/>
  <xacro:property name="base_iyy" value="{inr[iyy]:g}"/>
  <xacro:property name="base_izz" value="{inr[izz]:g}"/>
  <xacro:property name="base_ixy" value="{inr[ixy]:g}"/>
  <xacro:property name="base_ixz" value="{inr[ixz]:g}"/>
  <xacro:property name="base_iyz" value="{inr[iyz]:g}"/>

  <!-- base_link center height above ground (base_footprint -> base_link).
       DERIVED as wheel_radius - wheel_z so axle height always equals wheel
       radius (wheels touch ground in sim). Ground clearance
       = base_center_z - base_height/2 = {clearance:g} m. -->
  <xacro:property name="base_center_z" value="{bcz:g}"/>

  <!-- Wheels: {w[part]} -->
  <xacro:property name="wheel_radius" value="{w[radius_m]:g}"/>
  <xacro:property name="wheel_width"  value="{w[width_m]:g}"/>
  <xacro:property name="wheel_mass"   value="{w[mass_kg]:g}"/>
  <xacro:property name="wheel_x"      value="{w[x_offset_m]:g}"/>   <!-- +/- from center, fore/aft -->
  <xacro:property name="wheel_y"      value="{w[y_offset_m]:g}"/>   <!-- +/- from center, left/right (track/2) -->
  <xacro:property name="wheel_z"      value="{w[z_offset_m]:g}"/>  <!-- wheel center relative to base_link -->

  <!-- Derived: kept as one expression so it can never drift from wheel_y -->
  <xacro:property name="wheel_separation" value="${{2.0 * wheel_y}}"/>
</robot>
"""


CONFIG_H_TEMPLATE = """/* ============================ GENERATED FILE ============================
 * DO NOT EDIT. Generated by tools/build.py from design_params.yaml (firmware
 * section) + requirements yaml. Edit those and re-run `python3 tools/build.py`.
 * ======================================================================= */
#ifndef BUDDY_CONFIG_H
#define BUDDY_CONFIG_H

#define BUDDY_VEL_LIMIT_MMPS {vel_limit:d}   /* teleop max, requirements yaml */
#define BUDDY_CURRENT_LIMIT_MA {cur_limit:d} /* ADR-0005 driver limit */
#define BUDDY_WATCHDOG_MS {watchdog:d}       /* REQ_SAFE_002 */
#define BUDDY_TELEMETRY_HZ {telem:d}
#define BUDDY_CONTROL_HZ {control:d}
#define BUDDY_PWM_HZ {pwm:d}
#define BUDDY_WHEEL_RADIUS_UM {wheel_um:d}   /* micrometers, integer-exact */
#define BUDDY_ENC_COUNTS_PER_REV {cpr:d}     /* 4x-decoded counts at output shaft */

/* Per-wheel encoder sign (LF, LR, RF, RR). Applied in hw_encoder_count() so
   telemetry always reports positive = forward. Left/right motors are mirrored
   on a skid-steer, so one side is negated by geometry, not by miswiring.
   Source: {sign_src} — finalise at assembly. */
#define BUDDY_ENCODER_SIGN {{ {signs} }}

#endif /* BUDDY_CONFIG_H */
"""


def generate_firmware_config(reqs: dict) -> Path:
    fw = P["firmware"]
    out = ROOT / "firmware" / "drive_mcu" / "include" / "buddy_config.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(CONFIG_H_TEMPLATE.format(
        vel_limit=round(reqs["mobility"]["teleop_commissioning_max_mps"] * 1000),
        cur_limit=round(P["power"]["driver_current_limit_a"] * 1000),
        watchdog=fw["watchdog_ms"], telem=fw["telemetry_hz"],
        control=fw["control_hz"], pwm=fw["pwm_hz"],
        wheel_um=round(P["wheels"]["radius_m"] * 1e6),
        cpr=round(P["drive_motor"]["encoder_counts_per_rev_output"]),
        signs=", ".join(str(int(v)) for v in P["drive_motor"]["encoder_sign"]),
        sign_src=P["drive_motor"]["encoder_sign_source"],
    ), encoding="utf-8", newline="\n")
    return out


ZERO_COM = {"x": 0.0, "y": 0.0, "z": 0.0}
ZERO_INERTIA = {k: 0.0 for k in ("ixx", "iyy", "izz", "ixy", "ixz", "iyz")}


def generate_xacro() -> Path:
    """Write buddy_params.xacro from design_params.yaml.

    chassis.com_m and chassis.inertia_kgm2 are null until CAD measures them.
    While null, emit zeros and measured_inertia=false so the URDF keeps using
    its solid-box approximation; the zeros are never read in that branch.
    """
    c = P["chassis"]
    com, inertia = c.get("com_m"), c.get("inertia_kgm2")
    measured = com is not None and inertia is not None
    if measured:
        missing = [k for k in ZERO_INERTIA if k not in inertia] + \
                  [k for k in ZERO_COM if k not in com]
        if missing:
            raise SystemExit(
                f"chassis com_m/inertia_kgm2 are partially filled — missing {missing}. "
                "Fill every component or set both back to null; a half-measured "
                "inertia is worse than an honest box approximation.")
    out = ROOT / "robot_ws" / "src" / "buddy_description" / "urdf" / "buddy_params.xacro"
    out.write_text(XACRO_TEMPLATE.format(
        c=c, w=P["wheels"], bcz=base_center_z(), clearance=ground_clearance(),
        measured=str(measured).lower(),
        com=com if measured else ZERO_COM,
        inr=inertia if measured else ZERO_INERTIA), encoding="utf-8", newline="\n")
    return out


def export_notebook(nb_path: Path) -> Path:
    """Execute a marimo notebook and write its markdown export next to it."""
    spec = importlib.util.spec_from_file_location(nb_path.stem, nb_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    outputs, _defs = module.app.run()

    chunks = []
    for out in outputs:
        md = getattr(out, "_markdown_text", None)
        if md:
            chunks.append(md.strip())
    body = "\n\n".join(chunks)

    fm = FRONTMATTER.get(nb_path.stem, {"title": nb_path.stem, "type": "analysis"})
    fm_lines = "\n".join(f"{k}: {v}" for k, v in fm.items())
    # as_posix(): the banner is a shell command a reader copies, and it is
    # committed — it must not pick up backslashes when the build runs on Windows.
    banner = (f"<!-- GENERATED from {nb_path.name} by tools/build.py — edit the "
              f"notebook (marimo edit {nb_path.relative_to(ROOT).as_posix()}) or "
              f"design_params.yaml, then rebuild. -->")
    out_path = nb_path.with_suffix(".md")
    out_path.write_text(f"---\n{fm_lines}\n---\n{banner}\n\n{body}\n",
                        encoding="utf-8", newline="\n")
    return out_path


def main() -> int:
    problems = (buddy_calcs.validate() + buddy_power.validate()
                + check_integration_map.problems())
    if problems:
        for p in problems:
            print(f"VALIDATION FAILED: {p}", file=sys.stderr)
        return 1
    print(f"validation ok (ground clearance {ground_clearance():.3f} m; "
          f"integration map agrees with pin map, protocol and bridge node)")

    print(f"generated  {generate_xacro().relative_to(ROOT)}")

    import yaml as _yaml
    reqs = _yaml.safe_load(
        (ROOT / "docs" / "requirements" / "buddy_v0_1_requirements.yaml")
        .read_text(encoding="utf-8"))
    print(f"generated  {generate_firmware_config(reqs).relative_to(ROOT)}")

    for nb in sorted((ROOT / "docs" / "analysis").glob("*.py")):
        print(f"exported   {export_notebook(nb).relative_to(ROOT)}")

    for fig in sorted((ROOT / "tools" / "figures").glob("plot_*.py")):
        subprocess.run([sys.executable, str(fig)], check=True, cwd=ROOT,
                       capture_output=True)
        print(f"figure     {fig.stem}")

    csv = ROOT / "robot_ws" / "analysis" / "torque_sweep.csv"
    subprocess.run([sys.executable, str(ROOT / "robot_ws" / "tools" / "torque_sweep.py"),
                    "--csv", str(csv)], check=True, cwd=ROOT, capture_output=True)
    print(f"generated  {csv.relative_to(ROOT)}")

    # Schematics are generated artifacts too. Their electrical connectivity is
    # asserted separately (check_drive_wiring.py / check_system_wiring.py) —
    # run those after changing a harness; they need kicad-cli.
    for gen in ("gen_drive_wiring.py", "gen_system_wiring.py",
                "render_schematics.py"):
        r = subprocess.run([sys.executable, str(ROOT / "tools" / "kicad" / gen)],
                           check=True, cwd=ROOT, capture_output=True, text=True)
        print(f"schematic  {r.stdout.strip().splitlines()[-1]}")

    subprocess.run([sys.executable, str(ROOT / "tools" / "site" / "build_site.py")],
                   check=True, cwd=ROOT, capture_output=True)
    print("generated  site/ (view: python3 -m http.server -d site 8137)")
    print("build complete — review `git diff` for the effect of your parameter change")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
